// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WSOA.Server.Data;

#nullable disable

namespace WSOA.Server.Migrations
{
    [DbContext(typeof(WSOADbContext))]
    [Migration("20230811211200_InitializeDB")]
    partial class InitializeDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WSOA.Shared.Entity.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "Potrunks",
                            Password = "Trunks92!"
                        });
                });

            modelBuilder.Entity("WSOA.Shared.Entity.MainNavSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassIcon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MainNavSections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassIcon = "uil uil-estate",
                            Label = "Accueil",
                            Name = "Home",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            ClassIcon = "uil uil-chart-pie",
                            Label = "Statistique",
                            Name = "Statistical",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            ClassIcon = "uil uil-spade",
                            Label = "Tournoi",
                            Name = "Tournament",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            ClassIcon = "uil uil-user",
                            Label = "Compte",
                            Name = "Account",
                            Order = 4
                        });
                });

            modelBuilder.Entity("WSOA.Shared.Entity.Profile", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Code = "ADMIN",
                            Name = "Administrator"
                        },
                        new
                        {
                            Code = "ORGA",
                            Name = "Organizer"
                        },
                        new
                        {
                            Code = "PLAYER",
                            Name = "Player"
                        },
                        new
                        {
                            Code = "GUEST",
                            Name = "Guest"
                        });
                });

            modelBuilder.Entity("WSOA.Shared.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ProfileCode");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            FirstName = "Alexis",
                            LastName = "ARRIAL",
                            ProfileCode = "ADMIN"
                        });
                });

            modelBuilder.Entity("WSOA.Shared.Entity.User", b =>
                {
                    b.HasOne("WSOA.Shared.Entity.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WSOA.Shared.Entity.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
